name: TestProjectName
options:
  bundleIdPrefix: com.TestProjectName
packages:
    Fork:
        url: https://github.com/0xLeif/Fork
        from: 1.0.0
    o:
        url: https://github.com/0xOpenBytes/o
        from: 1.0.0
    c:
        url: https://github.com/0xOpenBytes/c
        from: 3.0.0
targets:
  TestProjectName:
    scheme:
      testTargets:
        - TestProjectNameTests
    info:
        path: TestProjectName/Info.plist
        properties:
          UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
          UILaunchScreen: [UILaunchScreen: []]
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [TestProjectName]
    dependencies:
      - package: Fork
      - package: o
      - package: c
    postCompileScripts:
        - script:
          script: |
                    export PATH="$PATH:/opt/homebrew/bin"
                    if which swiftlint > /dev/null; then
                    swiftlint
                    else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    fi
          name: Swiftlint
          TestProjectNamedOnDependencyAnalysis: false

  TestProjectNameTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: [TestProjectNameTests]
    info:
        path: TestProjectNameTests/Info.plist
    dependencies:
        - target: TestProjectName
