name: base
options:
  bundleIdPrefix: com.base
packages:
  Fork:
    url: https://github.com/0xLeif/Fork
    from: 1.0.0
  o:
    url: https://github.com/0xOpenBytes/o
    from: 1.0.0
  c:
    url: https://github.com/0xOpenBytes/c
    from: 3.0.0
schemes:
  base:
    build:
      targets:
        base: all
        baseUITests: [run, test]
  Screenshots:
    build:
      targets:
        base: all
        baseUITests: [run, test]
    test:
      targets:
        - baseUITests
    run:
      environmentVariables:
        SCREENSHOTS: "YES"
targets:
  base:
    scheme:
      testTargets:
        - baseTests
    info:
      path: base/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: [UILaunchScreen: []]
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [base]
    dependencies:
      - package: Fork
      - package: o
      - package: c
    postCompileScripts:
      - name: Swiftlint
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint > /dev/null; then
          swiftlint --config .swiftlint.yml
          else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false

  baseTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: [baseTests]
    info:
      path: baseTests/Info.plist
    dependencies:
      - target: base
  baseUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources: [baseUITests]
    info:
      path: baseUITests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      TEST_TARGET_NAME: base
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: "1.0"
      TARGETED_DEVICE_FAMILY: 1
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.base.UITests
