//
//  base template generated by OpenBytes on 12/15/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  ProfileScreen.swift
//

import SwiftUI

struct ProfileScreen: View {
    @ObservedObject var settings: AppSettings = AppSettings.shared

    var body: some View {
        Group {
            if let user = settings.user {
                VStack {
                    Text("Logged in: \(user.username)")

                    Button(
                        "Logout",
                        role: .destructive,
                        action: { settings.user = nil }
                    )
                }
            } else {
                RegisterScreen(
                    registerViewModel: RegisterViewModel(
                        // TODO: (base-Template) Update to Production
                        registerNetworking: NoDataFailureMockRegisterService()
                    )
                )
            }
        }
        .navigationTitle("Profile")
    }
}

struct ProfileScreen_Previews: PreviewProvider {
    static var previews: some View {
        ProfileScreen()
    }
}
