//
//  base template generated by OpenBytes on 12/15/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  CartographyView.swift
//

import SwiftUI

struct CartographyView<RootView: View>: View {
    @ObservedObject var path: CartographyPath
    let rootView: () -> RootView

    var body: some View {
        NavigationStack(path: $path.navigation) {
            rootView()
                .sheet(
                    item: $path.modal,
                    content: { modal in
                        modal.body()
                    }
                )
                .alert(
                    item: $path.alert,
                    content: { alert in
                        SwiftUI.Alert(
                            title: alert.title,
                            message: alert.message,
                            primaryButton: alert.primaryButton,
                            secondaryButton: alert.secondaryButton
                        )
                    }
                )
                .confirmationDialog(
                    path.actionSheet?.title ?? "",
                    isPresented: Binding(
                        get: { path.actionSheet != nil },
                        set: { newValue  in
                            if newValue == false {
                                path.actionSheet = nil
                            }
                        }
                    ),
                    presenting: path.actionSheet,
                    actions: { actionSheet in
                        actionSheet.actions()
                    },
                    message: { actionSheet in
                        actionSheet.message()
                    }
                )
                .modifier(ToastModifer(toast: $path.toast))
        }
    }
}

extension CartographyView {
    static func preview(_ content: @escaping () -> RootView) -> CartographyView {
        Navigation.shared.isPreview = true

        return CartographyView(path: Navigation.path, rootView: content)
    }
}
