//
//  base template generated by OpenBytes on 12/20/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Rob Maltese.
//  ToastStyle.swift
//

import SwiftUI

/// This allows us to define the style of the `ToastNotification` in a easy and clean manner.
/// - `toastColor`: Defines the color of the icon and the notification style of the type selected.
/// - `toastIcon`: Defines the icon displayed relevant to the overall notification type selected.
enum ToastStyle {
    case error
    case success
    case warning
    case info

    var toastColor: Color {
        switch self {
        case .error:
            return .red
        case .success:
            return .green
        case .warning:
            return .yellow
        case .info:
            return .blue
        }
    }

    var toastIcon: String {
        switch self {
        case .error:
            return "info.circle.fill"
        case .success:
            return "checkmark.circle.fill"
        case .warning:
            return "exclamationmark.circle.fill"
        case .info:
            return "info.circle.fill"
        }
    }
}
