//
//  base template generated by OpenBytes on 12/22/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  MockData.swift
//

import Foundation

extension Mock {
    static let users: [User] = [
        User(username: "Red User", email: "1@mock.dev", color: .red),
        User(username: "Green User", email: "2@mock.dev", color: .green),
        User(username: "Blue User", email: "3@mock.dev", color: .blue)
    ]
}
