//
//  base template generated by OpenBytes on 12/17/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Rob Maltese.
//  ErrorHandling.swift
//

import Foundation

struct ErrorHandling {
    /// Function allows for the passing of an `Error` which will display a forward facing toast message to the user.
    func handleError(error: Error) {
        #if DEBUG
        Navigation.path.toast(
            title: "Error",
            message: error.localizedDescription,
            style: .error
        )
        #else
        print("⚠️ Error! - \(error)")
        Navigation.path.toast(
            title: "Error",
            message: "There was an error registering your account, please try again.",
            style: .error
        )
        #endif
    }
}
