name: Feature Request
description: Request a new feature or enhancement
labels: ["Type: Enhancement"]
title: "[FEATURE]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the feature or enhancement
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give some additional information on the feature request like proposed solutions, links, screenshots, etc.
