name: General or Question
description: Questions and requests for support.
labels: ["Type: Question"]
title: "[QUESTION]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this task hasn't been already submitted by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your question or ask for support.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give some additional context or information here.
