name: Security Report
description: Report a security issue or vulnerability.
labels: ["Type: Security"]
title: "[SECURITY]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this task hasn't been already submitted by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the issue is
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Write out the steps to reproduce the error here (add or remove as many steps as needed)
      placeholder: |
        (e.g.:)
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What was it supposed to do?
      value: "The expected behavior for ... is ..."
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Media
      description: If applicable, add screenshots or videos to help explain your problem.

  - type: dropdown
    id: ios-version
    attributes:
      label: What version(s) of iOS did this you encounter this security issue on or it applies to?
      multiple: true
      options:
        - 16.x
        - 16.3 BETA
        - 16.2
        - 16.1.2
        - 16.1.1
        - 16.1
        - 16.0.3
        - 16.0.2
        - 16.0.1
        - Other (see description)
    validations:
      required: true

  - type: dropdown
    id: devices
    attributes:
      label: What device(s) are you seeing the problem on? (Optional)
      multiple: true
      options:
        - iPhone 14
        - iPhone 14 Plus
        - iPhone 14 Pro
        - iPhone 14 Pro Max
        - iPhone 13 
        - iPhone 13 mini
        - iPhone 13 Pro
        - iPhone 13 Pro Max
        - iPhone 12
        - iPhone 12 mini
        - iPhone 12 Pro
        - iPhone 12 Pro Max
        - iPhone 11
        - iPhone 11 Pro
        - iPhone 11 Pro Max
        - iPhone XS
        - iPhone XS Max
        - iPhone XR
        - iPhone X
        - iPhone 8
        - iPhone 8 Plus
        - iPhone SE (3rd generation)
        - iPhone SE (2nd generation)
        - iPad Pro 12.9-inch (6th generation)
        - iPad Pro 11-inch (4th generation)
        - iPad Pro 12.9-inch (5th generation)
        - iPad Pro 11-inch (3rd generation)
        - iPad Pro 12.9-inch (4th generation)
        - iPad Pro 11-inch (2nd generation)
        - iPad Pro 12.9-inch (3rd generation)
        - iPad Pro 11-inch (1st generation)
        - iPad Pro 12.9-inch (2nd generation)
        - iPad Pro 12.9-inch (1st generation)
        - iPad Pro 10.5-inch
        - iPad Pro 9.7-inch
        - iPad (10th generation)
        - iPad (9th generation)
        - iPad (8th generation)
        - iPad (7th generation)
        - iPad (6th generation)
        - iPad (5th generation)
        - iPad mini (6th generation)
        - iPad mini (5th generation)
        - iPad Air (5th generation)
        - iPad Air (4th generation)
        - iPad Air (3rd generation)

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give some additional information like proposed solutions, links, screenshots, etc.
