//
//  base template generated by OpenBytes on 12/20/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  ExampleAdapterTest.swift
//

import SwiftUI
import XCTest
@testable import base

final class ExampleAdapterTest: XCTestCase {
    func testAdapter() throws {
        let networkModel: NetworkUser = try XCTUnwrap(Mock.json(named: "mock-user"))

        let deviceModel = try UserAdapter.device(from: networkModel)

        XCTAssertEqual(deviceModel.id, networkModel.id)
        XCTAssertEqual(deviceModel.color, Color(red: 0, green: 0.5, blue: 0))
        XCTAssertEqual(deviceModel.username, networkModel.name)
        XCTAssertEqual(deviceModel.email, networkModel.email)
    }
}
