//
//  base template generated by OpenBytes on 12/21/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Rob Maltese.
//  RegisterViewModel.swift
//

import Foundation

/**
 The `RegisterViewModel` conforms to type `ObservableObject`,
 and acts as mediator between the view and the networking layer.
 */
class RegisterViewModel: ObservableObject, ErrorHandling {
    private var registerNetworking: RegisterNetworking
    private var registerTask: Task<Void, Never>?

    var errorHandler: ErrorHandler

    @Published var username = ""
    @Published var email = ""
    @Published var password = ""
    @Published var confirmationPassword = ""

    init(
        registerNetworking: RegisterNetworking,
        errorHandler: ErrorHandler = ErrorHandler(
            plugins: [
                ToastErrorPlugin()
            ]
        )
    ) {
        self.registerNetworking = registerNetworking
        self.errorHandler = errorHandler
    }

    var areFieldsValidated: Bool {
        email.isEmpty || password.isEmpty
    }

    /// Triggered by the `RegisterScreen` view submit button,
    /// and sends the required parameters to the network layer function,
    /// and assigns the return to `AppSettings.shared.user`.
    @discardableResult
    func registerUser() -> Task<Void, Never> {
        let task = Task {
            do {
                let user = try await registerNetworking.register(
                    username: username,
                    email: email,
                    password: password,
                    passwordConfirmation: confirmationPassword
                )

                await MainActor.run {
                    AppSettings.shared.user = user
                }

                DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) {
                    Navigation.path.toast(
                        title: "Success",
                        message: "You have successfully registered an account.",
                        style: .success
                    )
                }
            } catch {
                errorHandler.handle(error: error)
            }
        }

        registerTask = task

        return task
    }
}
