//
//  base template generated by OpenBytes on 12/20/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  ImageCache.swift
//

import c
import Foundation
import SwiftUI

class ImageCache: ObservableObject {
    private var lock: NSLock = NSLock()
    private var cache: c.KeyedCache<URL> = .init()

    static var shared: ImageCache = ImageCache()

    var valuesInCache: [URL: Image] {
        cache.valuesInCache(ofType: Image.self)
    }

    private init() { }

    func get(_ key: URL) -> Image? {
        cache.get(key, as: Image.self)
    }

    func resolve(_ key: URL) throws -> Image {
        try cache.resolve(key, as: Image.self)
    }

    func set(image: Image, forKey key: URL) {
        lock.lock()
        cache.set(value: image, forKey: key)
        lock.unlock()
        objectWillChange.send()
    }

    func remove(_ key: URL) {
        lock.lock()
        cache.remove(key)
        lock.unlock()
        objectWillChange.send()
    }

    func contains(_ key: URL) -> Bool {
        cache.contains(key)
    }

    func require(keys: Set<URL>) throws -> Self {
        _ = try cache.require(keys: keys)

        return self
    }

    func require(_ key: URL) throws -> Self {
        _ = try cache.require(key)

        return self
    }
}
