//
//  base template generated by OpenBytes on 12/14/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  HomeScreen.swift
//

import SwiftUI

struct HomeScreen: View {
    @ObservedObject var settings: AppSettings = AppSettings.shared

    var body: some View {
        VStack {
            ImageView(
                url: URL(string: "https://avatars.githubusercontent.com/u/92551192?s=200&v=4"),
                content: { image in
                    image
                        .resizable()
                        .frame(width: 120, height: 120)
                        .padding()
                },
                placeholder: {
                    ProgressView()
                        .foregroundColor(.accentColor)
                        .frame(width: 120, height: 120)
                        .padding()
                }
            )
        }
        .navigationTitle("Hello, \(settings.user?.username ?? "World")!")
        .toolbar {
            Button(
                action: {
                    Navigation.path.modal {
                        NavigationStack {
                            AcknowledgmentView()
                        }
                    }
                },
                label: {
                    Image(systemName: "info.circle")
                }
            )
        }
    }
}

struct HomeScreen_Previews: PreviewProvider {
    static var previews: some View {
        HomeScreen()
    }
}
