//
//  base template generated by OpenBytes on 1/22/23.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by FullQueueDeveloper.
//  baseScreenshotTests.swift
//

import XCTest

final class baseScreenshotTests: XCTestCase {

  var app: XCUIApplication!

  override func setUpWithError() throws {
    continueAfterFailure = false

    let app = XCUIApplication()
    app.launchEnvironment["SCREENSHOTS"] = "YES"
    app.launchArguments.append("enable-testing")
    app.launch()
    self.app = app
  }

  func testScreenshots() {
    takeScreenshot(named: "Home")
  }

  private func takeScreenshot(named name: String) {
    let screenshot = XCUIScreen.main.screenshot()
    let attachment = XCTAttachment(
      uniformTypeIdentifier: "public.png",
      name: "\(name).png",
      payload: screenshot.pngRepresentation)
    attachment.lifetime = .keepAlways
    add(attachment)
  }
}
