//
//  base template generated by OpenBytes on 12/15/22.
//  Copyright (c) 2023 OpenBytes
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the conditions found at the following link:
//  https://github.com/0xOpenBytes/ios-BASE/blob/main/LICENSE
//
// Created by Leif.
//  SearchScreen.swift
//

import SwiftUI

struct SearchScreen: View {
    var body: some View {
        List {
            Button(
                action: { Navigation.path.push(Date()) },
                label: { Text("Push") }
            )

            Button(
                action: { Navigation.path.modal { Text("Modal") } },
                label: { Text("Modal") }
            )

            Button(
                action: {
                    Navigation.path.alert(
                        title: Text("Alert Title"),
                        primaryButton: .default(Text("Done")),
                        secondaryButton: .cancel()
                    )
                },
                label: { Text("Alert") }
            )

            Button(
                action: {
                    Navigation.path.actionSheet(
                        title: "Action Sheet Title",
                        actions: {
                            Button(
                                action: { print("Hi") },
                                label: { Text("Say Hi") }
                            )
                        },
                        message: { Text("Action Sheet Message") }
                    )
                },
                label: { Text("Action Sheet") }
            )

            Button {
                Navigation.path.toast(
                    title: "Toast Title",
                    message: "This is a toast message and can be fairly long if needed.",
                    style: .error
                )
            } label: {
                Text("Toast Alert")
            }

        }
        .navigationDestination(
            for: Date.self,
            destination: { date in
                Text(date, format: .dateTime)
            }
        )
        .navigationTitle("Search")
    }
}

struct SearchScreen_Previews: PreviewProvider {
    static var previews: some View {
        CartographyView.preview {
            SearchScreen()
        }
    }
}
