name: CI
'on':
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'
      - name: Build
        run: >
          cd base

          xcodebuild build -project base.xcodeproj -scheme base clean build -sdk
          iphoneos CODE_SIGNING_ALLOWED=No
      - name: Tests
        run: >
          cd base

          xcodebuild test -project base.xcodeproj -scheme base clean build -sdk
          iphoneos -destination "platform=iOS Simulator,OS=16.1,
          name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
