# yamllint disable rule:line-length
name: CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"
      - run: brew bundle
      - run: swift package --package-path Swish resolve
      - run: swift build --package-path Swish
      - name: Build
        run: >
          xcodebuild build -project base.xcodeproj -scheme base clean
          build -sdk iphoneos CODE_SIGNING_ALLOWED=No
      - name: Tests
        run: >
          xcodebuild test -project base.xcodeproj -scheme base clean
          build -sdk iphoneos -destination "platform=iOS
          Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No

# yamllint enable rule:line-length
