name: docc
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"
      - name: Development dependencies
        run: brew bundle
      - name: Development scripts build
        run: swish -b
      - name: Generate project
        run: swish xcodeproj
      - name: docbuild
        run: |
          xcodebuild docbuild -scheme base \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/base.doccarchive \
            --hosting-base-path base \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/scribe\"</base>" > docs/index.html;
      - name: artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
